general {
    # Use uwsm so hyprlock stays connected to your authentication agents
    lock_cmd = pidof hyprlock || uwsm app -- hyprlock
    
    # lock before suspend.
    before_sleep_cmd = loginctl lock-session    
    
    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# === MONITOR DIM ===
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10%        
    on-resume = brightnessctl -r                 
}

# === LOCKSCREEN ===
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# === TURN OFF SCREEN ===
listener {
    timeout = 330                                                     
    on-timeout = hyprctl dispatch dpms off                            
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          
}

# === SUSPEND ===
listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend-then-hibernate
}