################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1,2880x1800@120,auto,1.879,bitdepth,10,cm,srgb

xwayland {
  force_zero_scaling = true
}

decoration {
    screen_shader = ~/.config/hypr/shaders/desaturate.glsl
}