monitorv2 {
    output = eDP-1
    mode = 2880x1800@120
    position = 0x0
    scale = 1.8
    bitdepth = 10
    cm = dcip3
    vrr = 1  # 1 = Always on, 2 = fullscreen only, 3 = only game or video
    supports_wide_color = 1
    supports_hdr = 1
    sdrbrightness = 1.2
    sdrsaturation = 1
    sdr_min_luminance = 0.0005  # Allow true black in SDR mode
    sdr_max_luminance = 80
    min_luminance = 0.0005
    max_luminance = 400
}

render {
    cm_auto_hdr = 0
    direct_scanout = true
}

xwayland {
    force_zero_scaling = true
}