[config]

[templates.foot]
input_path = "~/.config/noctalia/templates/foot"
output_path = "~/.config/foot/themes/foot"

[templates.hyprland]
input_path = "~/.config/noctalia/templates/hyprland.lua"
output_path = "~/.config/hypr/modules/colors.lua"
